# -*- encoding: utf-8 -*-
require 'open-uri'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Genre.delete_all
["Spot", "Eat", "Stay", "Shopping", "Activity", "Event", "Access", "Tour", "Traffic"].each do |name|
  Genre.create(:name => name)
end

Category.delete_all
SubCategory.delete_all

["Place name", "Train Station", "Subway", "Airport"].each do |name|
  Genre.find_by_name("Spot").categories.create(:name => name)
end

["African", "American", "Japanese", "BBQ", "Cafe"].each do |name|
  Genre.find_by_name("Eat").categories.create(:name => name)
end

["Hotel", "Mortel", "Japanese Style"].each do |name|
  Genre.find_by_name("Stay").categories.create(:name => name)
end

["Mall", "Gift shop", "Miscellaneous Shop", "Music Store"].each do |name|
  Genre.find_by_name("Shopping").categories.create(:name => name)
end

["Area name", "Country"].each do |name|
  Category.find_by_name("Place name").sub_categories.create(:name => name)
end

PostType.delete_all

[
 {:name => "Text",  :body_required => true},
 {:name => "Photo", :attachment_required => true},
 {:name => "Video", :attachment_required => true},
 {:name => "Album"},
 {:name => "Link",  :link_required => true},
 {:name => "Review", :body_required => true},
 {:name => "Q&A", :body_required => true},
 {:name => "Quote", :body_required => true},
 {:name => "Comment", :body_required => true}
].each do |options|
  PostType.create(options)
end


Country.delete_all
[
 "Åland",
 "Albania",
 "Andorra",
 "Austria",
 "Armenia",
 "Azerbaijan",
 "Belarus",
 "Belgium",
 "Bosnia And Herzegovina",
 "Bulgaria",
 "Croatia",
 "Cyprus",
 "Czech Republic",
 "Denmark",
 "England",
 "Estonia",
 "Faroe Islands",
 "Finland",
 "France",
 "Georgia",
 "Germany",
 "Gibraltar",
 "Greece",
 "Greenland",
 "Guernsey",
 "Hungary",
 "Iceland",
 "Ireland",
 "Isle of Man",
 "Italy",
 "Jersey",
 "Latvia",
 "Liechtenstein",
 "Lithuania",
 "Luxembourg",
 "Macedonia",
 "Malta",
 "Moldova",
 "Monaco",
 "Montenegro",
 "Netherlands",
 "Northern Ireland",
 "Norway",
 "Poland",
 "Portugal",
 "Romania",
 "Russia",
 "San Marino",
 "Scotland",
 "Serbia",
 "Slovakia",
 "Slovenia",
 "Spain",
 "Svalbard",
 "Sweden",
 "Switzerland",
 "Turkey",
 "Ukraine",
 "Vatican City",
 "Wales",
 "Afghanistan",
 "Bangladesh",
 "Bhutan",
 "Brunei",
 "Cambodia",
 "China",
 "East Timor",
 "Hong Kong (Special Administrative region of China)",
 "India",
 "Indonesia",
 "Japan",
 "Kazakhstan",
 "Kyrgyzstan",
 "Laos",
 "Macau (Special Administrative region of China)",
 "Malaysia",
 "Republic of Maldives",
 "Mongolia",
 "Myanmar",
 "Nepal",
 "North Korea",
 "Pakistan",
 "Philippines",
 "Russia",
 "Singapore",
 "South Korea",
 "Sri Lanka",
 "Taiwan",
 "Tajikistan",
 "Thailand",
 "Turkmenistan",
 "Uzbekistan",
 "Vietnam",
 "Bahrain",
 "Egypt",
 "Iran",
 "Iraq",
 "Israel",
 "Jordan",
 "Kuwait",
 "Lebanon",
 "Oman",
 "Qatar",
 "Saudi Arabia",
 "State of Palestine",
 "Sudan",
 "Syria",
 "Turkey",
 "United Arab Emirates",
 "Yemen",
 "Bermuda",
 "Canada",
 "Greenland",
 "Belize",
 "Costa Rica",
 "El Salvador",
 "Guatemala",
 "Honduras",
 "Nicaragua",
 "Panama",
 "Mexico",
 "Anguilla",
 "Antigua and Barbuda",
 "Aruba",
 "Bahamas",
 "Barbados",
 "British Virgin Islands",
 "Cayman Islands",
 "Cuba",
 "Dominica",
 "Dominican Republic",
 "Grenada",
 "Guadeloupe",
 "Haiti",
 "Jamaica",
 "Martinique",
 "Montserrat",
 "Netherlands Antilles",
 "Puerto Rico",
 "Saint Barthélemy",
 "Saint Lucia",
 "Saint Kitts and Nevis",
 "Saint Martin",
 "Saint Vincent and the Grenadines",
 "Trinidad and Tobago",
 "Turks and Caicos Islands",
 "United States Virgin Islands",
 "Saint Pierre and Miquelon",
 "United States of America",
 "Algeria",
 "Angola",
 "Ascension Island (U.K.)",
 "Benin",
 "Botswana",
 "Burkina Faso",
 "Burundi",
 "Cameroon",
 "Cape Verde",
 "Central African Republic",
 "Chad",
 "Comoros",
 "Cote d'Ivoire",
 "Democratic Republic of Congo",
 "Djibouti",
 "Egypt",
 "Equatorial Guinea",
 "Eritrea",
 "Ethiopia",
 "Gabon",
 "Gambia",
 "Ghana",
 "Guinea",
 "Guinea Bissau",
 "Kenya",
 "Lesotho",
 "Liberia",
 "Libya",
 "Madagascar",
 "Malawi",
 "Mali",
 "Mauritania",
 "Mauritius",
 "Mayotte (France)",
 "Morocco",
 "Mozambique",
 "Namibia",
 "Niger",
 "Nigeria",
 "Republic of Congo",
 "Reunion (France)",
 "Rwanda",
 "Saint Helena (U.K.)",
 "Sao Tome and Principe",
 "Senegal",
 "Seychelles",
 "Sierra Leone",
 "Somalia",
 "South Africa",
 "Sudan",
 "Swaziland",
 "Tanzania",
 "Togo",
 "Tristan da Cunha (U.K.)",
 "Tunisia",
 "Uganda",
 "Western Sahara",
 "Zambia",
 "Zimbabwe",
 "American Samoa",
 "Australia",
 "Christmas Island",
 "Cocos Islands",
 "Cook Islands",
 "Easter Island",
 "Fiji",
 "French Polynesia",
 "Guam",
 "Kiribati",
 "Marshall Islands",
 "Micronesia",
 "Nauru",
 "New Caledonia",
 "New Zealand",
 "Niue",
 "Norfolk Island",
 "Northern Mariana Islands",
 "Palau",
 "Papua New Guinea",
 "Pitcairn Islands",
 "Samoa",
 "Solomon Islands",
 "Tokelau",
 "Tonga",
 "Tuvalu",
 "Vanuatu",
 "Wallis and Futuna Islands",
 "Argentina",
 "Bolivia",
 "Brazil",
 "Chile",
 "Colombia",
 "Ecuador",
 "Falkland Islands",
 "French Guiana",
 "Guyana",
 "Paraguay",
 "Peru",
 "Suriname",
 "Uruguay",
 "Venezuela"].each do |name|
    Country.create :name => name
end
