class CreateAreas < ActiveRecord::Migration
  def self.up
    create_table :areas do |t|
      t.string :name
      t.timestamps
    end

    Country.delete_all
    Area.delete_all
    Page.delete_all("area_id is not null")
    Page.delete_all("country_id is not null")
    {"Africa" => ["Algeria",
                 "Angola",
                 "Ascension Island (U.K.)",
                 "Benin",
                 "Botswana",
                 "Burkina Faso",
                 "Burundi",
                 "Cameroon",
                 "Cape Verde",
                 "Central African Republic",
                 "Chad",
                 "Comoros",
                 "Cote d'Ivoire",
                 "Democratic Republic of Congo",
                 "Djibouti",
                 "Egypt",
                 "Equatorial Guinea",
                 "Eritrea",
                 "Ethiopia",
                 "Gabon",
                 "Gambia",
                 "Ghana",
                 "Guinea",
                 "Guinea Bissau",
                 "Kenya",
                 "Lesotho",
                 "Liberia",
                 "Libya",
                 "Madagascar",
                 "Malawi",
                 "Mali",
                 "Mauritania",
                 "Mauritius",
                 "Mayotte (France)",
                 "Morocco",
                 "Mozambique",
                 "Namibia",
                 "Niger",
                 "Nigeria",
                 "Republic of Congo",
                 "Reunion (France)",
                 "Rwanda",
                 "Saint Helena (U.K.)",
                 "Sao Tome and Principe",
                 "Senegal",
                 "Seychelles",
                 "Sierra Leone",
                 "Somalia",
                 "South Africa",
                 "Sudan",
                 "Swaziland",
                 "Tanzania",
                 "Togo",
                 "Tristan da Cunha (U.K.)",
                 "Tunisia",
                 "Uganda",
                 "Western Sahara",
                 "Zambia",
                 "Zimbabwe"],
      "Asia" => [
                 "Afghanistan",
                 "Bangladesh",
                 "Bhutan",
                 "Brunei",
                 "Cambodia",
                 "China",
                 "East Timor",
                 "Hong Kong (Special Administrative region of China)",
                 "India",
                 "Indonesia",
                 "Japan",
                 "Kazakhstan",
                 "Kyrgyzstan",
                 "Laos",
                 "Macau (Special Administrative region of China)",
                 "Malaysia",
                 "Republic of Maldives",
                 "Mongolia",
                 "Myanmar",
                 "Nepal",
                 "North Korea",
                 "Pakistan",
                 "Philippines",
                 "Russia",
                 "Singapore",
                 "South Korea",
                 "Sri Lanka",
                 "Taiwan",
                 "Tajikistan",
                 "Thailand",
                 "Turkmenistan",
                 "Uzbekistan",
                 "Vietnam"],
      "Caribbean" => [
                      "Anguilla",
                      "Antigua and Barbuda",
                      "Aruba",
                      "Bahamas",
                      "Barbados",
                      "British Virgin Islands",
                      "Cayman Islands",
                      "Cuba",
                      "Dominica",
                      "Dominican Republic",
                      "Grenada",
                      "Guadeloupe",
                      "Haiti",
                      "Jamaica",
                      "Martinique",
                      "Montserrat",
                      "Netherlands Antilles",
                      "Puerto Rico",
                      "Saint Barthélemy",
                      "Saint Lucia",
                      "Saint Kitts and Nevis",
                      "Saint Martin",
                      "Saint Vincent and the Grenadines",
                      "Trinidad and Tobago",
                      "Turks and Caicos Islands",
                      "United States Virgin Islands",
                     ],
      "Central America" => [
                            "Belize",
                            "Costa Rica",
                            "El Salvador",
                            "Guatemala",
                            "Honduras",
                            "Nicaragua",
                            "Panama"],
      "Europe" => [
                   "Åland",
                   "Albania",
                   "Andorra",
                   "Austria",
                   "Armenia",
                   "Azerbaijan",
                   "Belarus",
                   "Belgium",
                   "Bosnia And Herzegovina",
                   "Bulgaria",
                   "Croatia",
                   "Cyprus",
                   "Czech Republic",
                   "Denmark",
                   "England",
                   "Estonia",
                   "Faroe Islands",
                   "Finland",
                   "France",
                   "Georgia",
                   "Germany",
                   "Gibraltar",
                   "Greece",
                   "Greenland",
                   "Guernsey",
                   "Hungary",
                   "Iceland",
                   "Ireland",
                   "Isle of Man",
                   "Italy",
                   "Jersey",
                   "Latvia",
                   "Liechtenstein",
                   "Lithuania",
                   "Luxembourg",
                   "Macedonia",
                   "Malta",
                   "Moldova",
                   "Monaco",
                   "Montenegro",
                   "Netherlands",
                   "Northern Ireland",
                   "Norway",
                   "Poland",
                   "Portugal",
                   "Romania",
                   "Russia",
                   "San Marino",
                   "Scotland",
                   "Serbia",
                   "Slovakia",
                   "Slovenia",
                   "Spain",
                   "Svalbard",
                   "Sweden",
                   "Switzerland",
                   "Turkey",
                   "Ukraine",
                   "Vatican City",
                   "Wales"],
      "Middle East" => [
                        "Bahrain",
                        "Egypt",
                        "Iran",
                        "Iraq",
                        "Israel",
                        "Jordan",
                        "Kuwait",
                        "Lebanon",
                        "Oman",
                        "Qatar",
                        "Saudi Arabia",
                        "State of Palestine",
                        "Sudan",
                        "Syria",
                        "Turkey",
                        "United Arab Emirates",
                        "Yemen"],
      "North America" => [
                          "Bermuda",
                          "Canada",
                          "Greenland",
                          "Mexico",
                          "Saint Pierre and Miquelon",
                          "United States of America"],
      "Oceania" => [
                    "American Samoa",
                    "Australia",
                    "Christmas Island",
                    "Cocos Islands",
                    "Cook Islands",
                    "Easter Island",
                    "Fiji",
                    "French Polynesia",
                    "Guam",
                    "Kiribati",
                    "Marshall Islands",
                    "Micronesia",
                    "Nauru",
                    "New Caledonia",
                    "New Zealand",
                    "Niue",
                    "Norfolk Island",
                    "Northern Mariana Islands",
                    "Palau",
                    "Papua New Guinea",
                    "Pitcairn Islands",
                    "Samoa",
                    "Solomon Islands",
                    "Tokelau",
                    "Tonga",
                    "Tuvalu",
                    "Vanuatu",
                    "Wallis and Futuna Islands"],
      "South America" => [
                          "Argentina",
                          "Bolivia",
                          "Brazil",
                          "Chile",
                          "Colombia",
                          "Ecuador",
                          "Falkland Islands",
                          "French Guiana",
                          "Guyana",
                          "Paraguay",
                          "Peru",
                          "Suriname",
                          "Uruguay",
                          "Venezuela"]
    }.each do |area_name, ary|
      if (area = Page.find_by_title(area_name))
        area = Area.find_by_name(area_name)
      else
        area = Area.create :name => area_name
        json = JSON.parse(open("http://maps.googleapis.com/maps/api/geocode/json?address=#{CGI.escape area_name}&sensor=true").read)
        puts area_name
        puts json
        area_page = Page.create :title => area.name, :latitude => json["results"][0]["geometry"]["location"]["lat"], :longitude => json["results"][0]["geometry"]["location"]["lng"], :area => area, :genre => Genre.find_by_name("Spot"), :category => Category.find_by_name("Place name"), :sub_category => SubCategory.find_by_name("Area name")
      end
      ary.each do |name|
        if (country = Page.find_by_title(name))
        else
          json = JSON.parse(open("http://maps.googleapis.com/maps/api/geocode/json?address=#{CGI.escape name}&sensor=true").read)
          puts name
          puts json
          country = area.countries.create :name => name, :area => area
          page = Page.create :title => name, :latitude => json["results"][0]["geometry"]["location"]["lat"], :longitude => json["results"][0]["geometry"]["location"]["lng"], :area => area, :country => country, :genre => Genre.find_by_name("Spot"), :category => Category.find_by_name("Place name"), :sub_category => SubCategory.find_by_name("Country")
          area_page.pages << page
          area_page.save
        end
      end
    end
  end

  def self.down
    drop_table :areas
  end
end
